=== david-branco/anywhere/uploads/grades/grade.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT grade  (class, teachers, work+) >
    <!ELEMENT class (cname, academic_year, course, institution) > 
        <!ATTLIST  class id CDATA #REQUIRED >
        <!ELEMENT  cname (#PCDATA) >
        <!ELEMENT  academic_year (#PCDATA) >
        <!ELEMENT  course (#PCDATA) >
        <!ELEMENT  institution (#PCDATA) >
    
    <!ELEMENT teachers (teacher+) >
        <!ELEMENT teacher (tname, tnumber, temail)>
        <!ATTLIST teacher id CDATA #REQUIRED >
        <!ELEMENT tname (#PCDATA) >
        <!ELEMENT tnumber (#PCDATA) >
        <!ELEMENT temail (#PCDATA) >

    <!ELEMENT work (wname, importance, workteam*) >
        <!ATTLIST work id CDATA #REQUIRED >
        <!ELEMENT wname (#PCDATA) >
        <!ELEMENT importance (#PCDATA) >
        <!ELEMENT workteam (wtname, member*) >
            <!ATTLIST  workteam id CDATA #REQUIRED >
            <!ELEMENT  wtname (#PCDATA) >
            <!ELEMENT member (mname, mnumber, memail, evaluation?)>
                <!ATTLIST  member id CDATA #REQUIRED >
                <!ELEMENT  mname (#PCDATA) >
                <!ELEMENT  mnumber (#PCDATA) >
                <!ELEMENT  memail (#PCDATA) >
                <!ELEMENT  evaluation (#PCDATA) >

=== david-branco/anywhere/ficheiros_teste/xml/ClassGood.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grade SYSTEM "../grade.dtd">
<grade>
  <class id="1">
    <cname>Processamento de Linguagens e Compiladores</cname>
    <academic_year>2013/2014</academic_year>
    <course>LCC</course>
    <institution>UMinho</institution>
  </class>
  <teachers>
    <teacher id="1">
      <tname>José Carlos Ramalho</tname>
      <tnumber>p1000</tnumber>
      <temail>jcr2@di.uminho.pt</temail>
    </teacher>
    <teacher id="2">
      <tname>Pedro Rangel Henriques</tname>
      <tnumber>p1001</tnumber>
      <temail>prh2@di.uminho.pt</temail>
    </teacher>
  </teachers>
  <work id="1">
    <wname>Trabalho Prático nº 1</wname>
    <importance>50</importance>
    <workteam id="1">
      <wtname>Grupo 1</wtname>
      <member id="1">
        <mname>David Branco</mname>
        <mnumber>a55878</mnumber>
        <memail>davidbranco88@gmail.com</memail>
        <evaluation>20</evaluation>
      </member>
      <member id="2">
        <mname>Bruno Araujo</mname>
        <mnumber>pg26216</mnumber>
        <memail>brunotiagoaraujo@gmail.com</memail>
        <evaluation>20</evaluation>
      </member>
      <member id="3">
        <mname>Ricardo Silva</mname>
        <mnumber>a52839</mnumber>
        <memail>kaiserric@gmail.com</memail>
        <evaluation>15</evaluation>
      </member>
    </workteam>
    <workteam id="2">
      <wtname>Grupo 2</wtname>
      <member id="4">
        <mname>Nelson Brandão</mname>
        <mnumber>a50001</mnumber>
        <memail>nelson@gmail.com</memail>
        <evaluation>14</evaluation>
      </member>
      <member id="5">
        <mname>Ramon Rodrigues</mname>
        <mnumber>a50002</mnumber>
        <memail>ramon@gmail.com</memail>
        <evaluation>14</evaluation>
      </member>
      <member id="6">
        <mname>Luis Lima</mname>
        <mnumber>a50003</mnumber>
        <memail>luis@gmail.com</memail>
        <evaluation>14</evaluation>
      </member>
    </workteam>
    <workteam id="3">
      <wtname>Grupo 3</wtname>
      <member id="7">
        <mname>Jorge Lobo Teixeira Lopes</mname>
        <mnumber>a53898</mnumber>
        <memail> jorgelobolopes@gmail.com</memail>
        <evaluation>13</evaluation>
      </member>
      <member id="8">
        <mname>Paulo Alexandre Ribeiro Silva</mname>
        <mnumber>a62144</mnumber>
        <memail> pauloribeirosilva92@gmail.com</memail>
        <evaluation>13</evaluation>
      </member>
    </workteam>
    <workteam id="4">
      <wtname>Grupo 4</wtname>
      <member id="24">
        <mname>Daniel José Ferreira Novais</mname>
        <mnumber>a60001</mnumber>
        <memail>danielnovais92@gmail.com</memail>
        <evaluation>12</evaluation>
      </member>
      <member id="25">
        <mname>Eduardo José Dias Pessoa</mname>
        <mnumber>a60002</mnumber>
        <memail>eduardo.jose.pessoa@gmail.com</memail>
        <evaluation>12</evaluation>
      </member>
    </workteam>
    <workteam id="5">
      <wtname>Grupo 5</wtname>
      <member id="26">
        <mname>Miguel Angelo Gomes da Costa</mname>
        <mnumber>a60004</mnumber>
        <memail>miguel.angelo.cst@gmail.com</memail>
        <evaluation>11</evaluation>
      </member>
      <member id="27">
        <mname>Pedro Sérgio Azevedo</mname>
        <mnumber>a54065</mnumber>
        <memail>a54065@alunos.uminho.pt </memail>
        <evaluation>11</evaluation>
      </member>
    </workteam>
    <workteam id="6">
      <wtname>Grupo 6</wtname>
      <member id="28">
        <mname>Ricardo José Sampaio</mname>
        <mnumber>a58902</mnumber>
        <memail>a58902@alunos.uminho.pt</memail>
        <evaluation>10</evaluation>
      </member>
      <member id="29">
        <mname>Tiago Filipe Andrade Brito</mname>
        <mnumber>a60005</mnumber>
        <memail> tiago.brito3@gmail.com</memail>
        <evaluation>10</evaluation>
      </member>
    </workteam>
  </work>
  <work id="2">
    <wname>Trabalho Prático nº2</wname>
    <importance>50</importance>
    <workteam id="7">
      <wtname>Grupo 1</wtname>
      <member id="1">
        <mname>David Branco</mname>
        <mnumber>a55878</mnumber>
        <memail>davidbranco88@gmail.com</memail>
        <evaluation>50</evaluation>
      </member>
      <member id="2">
        <mname>Bruno Araujo</mname>
        <mnumber>pg26216</mnumber>
        <memail>brunotiagoaraujo@gmail.com</memail>
        <evaluation>15</evaluation>
      </member>
      <member id="3">
        <mname>Ricardo Silva</mname>
        <mnumber>a52839</mnumber>
        <memail>kaiserric@gmail.com</memail>
        <evaluation>15</evaluation>
      </member>
    </workteam>
    <workteam id="8">
      <wtname>Grupo 2</wtname>
      <member id="4">
        <mname>Nelson Brandão</mname>
        <mnumber>a50001</mnumber>
        <memail>nelson@gmail.com</memail>
        <evaluation>14</evaluation>
      </member>
      <member id="5">
        <mname>Ramon Rodrigues</mname>
        <mnumber>a50002</mnumber>
        <memail>ramon@gmail.com</memail>
        <evaluation>14</evaluation>
      </member>
      <member id="6">
        <mname>Luis Lima</mname>
        <mnumber>a50003</mnumber>
        <memail>luis@gmail.com</memail>
        <evaluation>14</evaluation>
      </member>
    </workteam>
    <workteam id="9">
      <wtname>Grupo 3</wtname>
      <member id="7">
        <mname>Jorge Lobo Teixeira Lopes</mname>
        <mnumber>a53898</mnumber>
        <memail> jorgelobolopes@gmail.com</memail>
        <evaluation>13</evaluation>
      </member>
      <member id="8">
        <mname>Paulo Alexandre Ribeiro Silva</mname>
        <mnumber>a62144</mnumber>
        <memail> pauloribeirosilva92@gmail.com</memail>
        <evaluation>13</evaluation>
      </member>
    </workteam>
    <workteam id="10">
      <wtname>Grupo 4</wtname>
      <member id="24">
        <mname>Daniel José Ferreira Novais</mname>
        <mnumber>a60001</mnumber>
        <memail>danielnovais92@gmail.com</memail>
        <evaluation>12</evaluation>
      </member>
      <member id="25">
        <mname>Eduardo José Dias Pessoa</mname>
        <mnumber>a60002</mnumber>
        <memail>eduardo.jose.pessoa@gmail.com</memail>
        <evaluation>12</evaluation>
      </member>
    </workteam>
    <workteam id="11">
      <wtname>Grupo 5</wtname>
      <member id="26">
        <mname>Miguel Angelo Gomes da Costa</mname>
        <mnumber>a60004</mnumber>
        <memail>miguel.angelo.cst@gmail.com</memail>
        <evaluation>11</evaluation>
      </member>
      <member id="27">
        <mname>Pedro Sérgio Azevedo</mname>
        <mnumber>a54065</mnumber>
        <memail>a54065@alunos.uminho.pt </memail>
        <evaluation>11</evaluation>
      </member>
    </workteam>
    <workteam id="12">
      <wtname>Grupo 6</wtname>
      <member id="28">
        <mname>Ricardo José Sampaio</mname>
        <mnumber>a58902</mnumber>
        <memail>a58902@alunos.uminho.pt</memail>
        <evaluation>10</evaluation>
      </member>
      <member id="29">
        <mname>Tiago Filipe Andrade Brito</mname>
        <mnumber>a60005</mnumber>
        <memail> tiago.brito3@gmail.com</memail>
        <evaluation>10</evaluation>
      </member>
    </workteam>
  </work>
</grade>
